import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody, CuboidCollider } from "@react-three/rapier";

export function Village2(props) {
  const { nodes, materials } = useGLTF("/models/Map_Muisca2.glb");
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh" name="village">
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Land.geometry}
        material={materials['Grass Land']}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Land2.geometry}
          material={materials.Arbol2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Land3.geometry}
          material={materials.ArbolTras}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass1001.geometry}
          material={materials.GrassTras}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass1001_1.geometry}
          material={materials.Grass4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass1001_2.geometry}
          material={materials.Grass2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Thatched_roof_3.geometry}
          material={materials.straw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Thatched_roof_4.geometry}
          material={materials.Clay}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Thatched_roof_5.geometry}
          material={materials.wood1}
        />
      </mesh>
      <group position={[0, 23.258, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019.geometry}
          material={materials['Clay.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_1.geometry}
          material={materials['wood1.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_2.geometry}
          material={materials['wood1.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_3.geometry}
          material={materials['wood1.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_4.geometry}
          material={materials['wood1.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_5.geometry}
          material={materials['wood1.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_6.geometry}
          material={materials['wood1.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_7.geometry}
          material={materials['wood1.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_8.geometry}
          material={materials['straw.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_9.geometry}
          material={materials['straw.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_10.geometry}
          material={materials['straw.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_11.geometry}
          material={materials['straw.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_12.geometry}
          material={materials['straw.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_13.geometry}
          material={materials['straw.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_14.geometry}
          material={materials['straw.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_15.geometry}
          material={materials['Wood.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_16.geometry}
          material={materials['Steel.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_17.geometry}
          material={materials['Clay.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_18.geometry}
          material={materials['Clay.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_19.geometry}
          material={materials['Clay.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_20.geometry}
          material={materials['Clay.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_21.geometry}
          material={materials['Clay.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClayHouse019_22.geometry}
          material={materials['Clay.013']}
        />
      </group>
      <group position={[0, 23.258, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HomeClay001.geometry}
          material={materials['Clay.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HomeClay001_1.geometry}
          material={materials['wood2.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HomeClay001_2.geometry}
          material={materials['straw.013']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arbol.geometry}
        material={materials.ArbolTras}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arbol2.geometry}
        material={materials.Arbol2}
        rotation={[Math.PI / 2, 0, 0]}
        scale={7.601}
      />
      <group position={[-1.158, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass1001_3.geometry}
          material={materials.GrassTras}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass1001_4.geometry}
          material={materials.Grass4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass1001_5.geometry}
          material={materials.Grass2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thatched_roof.geometry}
        material={materials.straw}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thatched_roof_1.geometry}
        material={materials.Clay}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thatched_roof_2.geometry}
        material={materials.wood1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landscape001.geometry}
        material={materials['Forest Ground']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landscape001_1.geometry}
        material={materials['Forest Ground.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ToolThree002.geometry}
        material={materials['Steel.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ToolThree002_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ToolThree002_2.geometry}
        material={materials.Steel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ToolThree002_3.geometry}
        material={materials.Wood}
      />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/Map_Muisca2.glb");
export default Village2;
